## The “HelixCare AI Governance Platform” Video Script

| Time | Visual Instruction | Voiceover Script |
|---|---|---|
| 0:00 – 0:20 | **SHOW IMAGE 1 (Legacy AI Ops Console)** | We worked on a healthcare AI operations platform where the client had internal AI agents, but the system around them was not enterprise-ready. Governance was fragmented, approvals were manual, observability was incomplete, and provider failures were hard to track. |
| 0:20 – 0:40 | **SHOW IMAGE 2 (Legacy Dashboard Problem Areas)** | The risk was clear: clinical AI requests were moving through the platform without strong operational controls. There were missing trace IDs, stale approval workflows, no reliable fallback routing, and limited visibility into what the AI system was doing in real time. |
| 0:40 – 1:00 | **SHOW IMAGE 3 (Architecture / Pipeline Overview)** | So we redesigned the solution as a governed AI operations platform. The architecture now includes an AI Control Plane, LLM Gateway, Governance Engine, Human Approval Workflow, Prometheus telemetry, Grafana dashboards, and a release pipeline that validates each layer. |
| 1:00 – 1:25 | **SHOW GITHUB ACTIONS PIPELINE** | This pipeline is mapped directly to the architecture. It validates the Platform Blueprint, AI Control Plane, LLM Gateway, Governance Engine, Observability Stack, Operations Workflow, Release Evidence, and Production Summary before the platform is considered ready. |
| 1:25 – 1:50 | **SHOW TERMINAL RUNNING PLATFORM SCRIPT** | Now we start the runtime platform. Docker Compose brings up the Agent API, LLM Gateway, Prometheus, Grafana, and NGINX. The script also generates AI traffic and simulates incidents so the monitoring layer shows live operational behavior. |
| 1:50 – 2:15 | **SHOW PROMETHEUS TARGETS / METRICS** | Prometheus confirms that the live services are being scraped. We can see metrics for governed AI requests, guardrail blocks, approval queue depth, fallback routing events, latency, token usage, and cost signals. |
| 2:15 – 2:40 | **SHOW GRAFANA DASHBOARD FULL SCREEN** | Grafana turns those metrics into an operations command center. The team can monitor AI throughput, clinical-risk escalations, human review queues, fallback routing, provider latency, and incident containment from one place. |
| 2:40 – 3:00 | **SHOW INCIDENT SIMULATION + FINAL DASHBOARD** | When a risky clinical request or provider degradation occurs, the platform does not silently fail. It escalates the request, stages it for human review, routes through fallback when needed, and produces release evidence. The final result is a governed, observable, and resilient healthcare AI platform. |
